package Day16_ExceptionHandling.Exception;

public class Exception02_CatchException {
    public static void main(String[] args) {

    }
}


